version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: perineum/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    container_name: frontend
    image: perineum/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    container_name: gateway
    image: perineum/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9000:80